// StudioWorth — Plugin + Gear Price Database
// Prices are MSRP list price in USD. No discounts. No judgment.
// Keys are lowercase normalized names for fuzzy matching.

const PRICES = {
  // ── Synths ───────────────────────────────────────────────────────
  "serum":              { name: "Xfer Serum",              price: 189,  brand: "Xfer Records",        category: "Synth" },
  "massive":            { name: "Massive",                 price: 149,  brand: "Native Instruments",   category: "Synth" },
  "massive x":          { name: "Massive X",               price: 199,  brand: "Native Instruments",   category: "Synth" },
  "sylenth1":           { name: "Sylenth1",                price: 189,  brand: "LennarDigital",        category: "Synth" },
  "omnisphere":         { name: "Omnisphere 2",            price: 499,  brand: "Spectrasonics",        category: "Synth" },
  "omnisphere 2":       { name: "Omnisphere 2",            price: 499,  brand: "Spectrasonics",        category: "Synth" },
  "keyscape":           { name: "Keyscape",                price: 399,  brand: "Spectrasonics",        category: "Synth" },
  "trilian":            { name: "Trilian",                 price: 299,  brand: "Spectrasonics",        category: "Synth" },
  "vital":              { name: "Vital",                   price: 80,   brand: "Matt Tytel",           category: "Synth" },
  "spire":              { name: "Spire",                   price: 189,  brand: "Reveal Sound",         category: "Synth" },
  "pigments":           { name: "Pigments",                price: 199,  brand: "Arturia",              category: "Synth" },
  "analog lab":         { name: "Analog Lab V",            price: 199,  brand: "Arturia",              category: "Synth" },
  "v collection":       { name: "V Collection",            price: 599,  brand: "Arturia",              category: "Synth" },
  "phase plant":        { name: "Phase Plant",             price: 199,  brand: "Kilohearts",           category: "Synth" },
  "surge":              { name: "Surge XT",                price: 0,    brand: "Surge Synth Team",     category: "Synth" },
  "diva":               { name: "Diva",                    price: 179,  brand: "u-he",                 category: "Synth" },
  "zebra2":             { name: "Zebra 2",                 price: 149,  brand: "u-he",                 category: "Synth" },
  "hive":               { name: "Hive 2",                  price: 149,  brand: "u-he",                 category: "Synth" },
  "repro":              { name: "Repro",                   price: 149,  brand: "u-he",                 category: "Synth" },
  "zebralette":         { name: "Zebralette",              price: 0,    brand: "u-he",                 category: "Synth" },
  "arp 2600":           { name: "ARP 2600 V",              price: 99,   brand: "Arturia",              category: "Synth" },
  "minimoog":           { name: "Mini V",                  price: 99,   brand: "Arturia",              category: "Synth" },
  "moog":               { name: "Moog Model D",            price: 99,   brand: "Moog Music",           category: "Synth" },
  "prophet":            { name: "Prophet-5 V",             price: 99,   brand: "Arturia",              category: "Synth" },
  "juno":               { name: "Juno-106 V",              price: 99,   brand: "Arturia",              category: "Synth" },
  "dx7":                { name: "DX7 V",                   price: 99,   brand: "Arturia",              category: "Synth" },
  "operator":           { name: "Operator",                price: 99,   brand: "Ableton",              category: "Synth" },
  "fm8":                { name: "FM8",                     price: 149,  brand: "Native Instruments",   category: "Synth" },
  "razor":              { name: "Razor",                   price: 99,   brand: "Native Instruments",   category: "Synth" },
  "absynth":            { name: "Absynth 5",               price: 149,  brand: "Native Instruments",   category: "Synth" },
  "reaktor":            { name: "Reaktor 6",               price: 199,  brand: "Native Instruments",   category: "Synth" },
  "lush-101":           { name: "Lush-101",                price: 89,   brand: "D16 Group",            category: "Synth" },
  "monark":             { name: "Monark",                  price: 99,   brand: "Native Instruments",   category: "Synth" },
  "prism":              { name: "Prism",                   price: 99,   brand: "Native Instruments",   category: "Synth" },
  "serum2":             { name: "Serum 2",                 price: 189,  brand: "Xfer Records",        category: "Synth" },
  "falcon":             { name: "Falcon",                  price: 299,  brand: "UVI",                  category: "Synth" },
  "kontakt":            { name: "Kontakt 8",               price: 299,  brand: "Native Instruments",   category: "Sampler" },
  "kontakt 8":          { name: "Kontakt 8",               price: 299,  brand: "Native Instruments",   category: "Sampler" },
  "kontakt 7":          { name: "Kontakt 7",               price: 399,  brand: "Native Instruments",   category: "Sampler" },
  "kontakt 6":          { name: "Kontakt 6",               price: 399,  brand: "Native Instruments",   category: "Sampler" },
  "kontakt player":     { name: "Kontakt Player",          price: 0,    brand: "Native Instruments",   category: "Sampler" },
  "battery":            { name: "Battery 4",               price: 199,  brand: "Native Instruments",   category: "Drums" },
  "battery 4":          { name: "Battery 4",               price: 199,  brand: "Native Instruments",   category: "Drums" },
  "backbone":           { name: "Backbone",                price: 149,  brand: "Steinberg",            category: "Drums" },
  "groove agent":       { name: "Groove Agent SE",         price: 0,    brand: "Steinberg",            category: "Drums" },
  "maschine":           { name: "Maschine 2",              price: 99,   brand: "Native Instruments",   category: "Drums" },
  "guitar rig":         { name: "Guitar Rig 7",            price: 149,  brand: "Native Instruments",   category: "Amp Sim" },
  "komplete":           { name: "Komplete 14",             price: 599,  brand: "Native Instruments",   category: "Bundle" },
  "komplete ultimate":  { name: "Komplete 14 Ultimate",    price: 1199, brand: "Native Instruments",   category: "Bundle" },
  "sampletank":         { name: "SampleTank 4",            price: 299,  brand: "IK Multimedia",        category: "Sampler" },
  "sampletank 4":       { name: "SampleTank 4",            price: 299,  brand: "IK Multimedia",        category: "Sampler" },
  "modo bass":          { name: "MODO Bass 2",             price: 149,  brand: "IK Multimedia",        category: "Instrument" },
  "modo bass 2":        { name: "MODO Bass 2",             price: 149,  brand: "IK Multimedia",        category: "Instrument" },
  "amp room":           { name: "Amp Room",                price: 149,  brand: "IK Multimedia",        category: "Amp Sim" },
  "bass amp room":      { name: "Bass Amp Room",           price: 99,   brand: "IK Multimedia",        category: "Amp Sim" },
  "vintage amp room":   { name: "Vintage Amp Room",        price: 99,   brand: "IK Multimedia",        category: "Amp Sim" },
  "uvi workstation":    { name: "UVI Workstation",         price: 0,    brand: "UVI",                  category: "Sampler" },
  "uviworkstation":     { name: "UVI Workstation",         price: 0,    brand: "UVI",                  category: "Sampler" },
  "uvi bloom":          { name: "UVI Bloom",               price: 49,   brand: "UVI",                  category: "Synth" },
  "model 82":           { name: "Model 82",                price: 149,  brand: "Softube",              category: "Synth" },
  "model 84":           { name: "Model 84",                price: 149,  brand: "Softube",              category: "Synth" },
  "heartbeat":          { name: "Heartbeat",               price: 149,  brand: "Output",               category: "Drums" },
  "noize":              { name: "Noize 2",                 price: 149,  brand: "Output",               category: "Synth" },
  "statement lead":     { name: "Statement Lead",          price: 149,  brand: "Output",               category: "Synth" },
  "tekno":              { name: "Tekno",                   price: 149,  brand: "Output",               category: "Synth" },

  // ── Output plugins ───────────────────────────────────────────────
  "portal":             { name: "Portal",                  price: 149,  brand: "Output",               category: "Effect" },
  "thermal":            { name: "Thermal",                 price: 149,  brand: "Output",               category: "Saturation" },
  "movement":           { name: "Movement",                price: 149,  brand: "Output",               category: "Effect" },
  "parallels":          { name: "Parallels",               price: 149,  brand: "Output",               category: "Effect" },
  "wasted space":       { name: "Wasted Space",            price: 149,  brand: "Output",               category: "Reverb" },
  "perfect room":       { name: "Perfect Room 2",          price: 149,  brand: "Output",               category: "Reverb" },
  "perfect room 2":     { name: "Perfect Room 2",          price: 149,  brand: "Output",               category: "Reverb" },
  "perfect plate":      { name: "Perfect Plate XL",        price: 149,  brand: "Output",               category: "Reverb" },
  "spaced out":         { name: "Spaced Out",              price: 149,  brand: "Output",               category: "Effect" },
  "crystalline":        { name: "Crystalline",             price: 49,   brand: "Baby Audio",           category: "Reverb" },

  // ── Eventide ─────────────────────────────────────────────────────
  "blackhole":          { name: "Blackhole",               price: 199,  brand: "Eventide",             category: "Reverb" },
  "ultrareverb":        { name: "UltraReverb",             price: 199,  brand: "Eventide",             category: "Reverb" },
  "micropitch":         { name: "MicroPitch",              price: 99,   brand: "Eventide",             category: "Effect" },
  "ultratap":           { name: "UltraTap",                price: 99,   brand: "Eventide",             category: "Delay" },
  "crushstation":       { name: "CrushStation",            price: 99,   brand: "Eventide",             category: "Saturation" },
  "shimmerverb":        { name: "ShimmerVerb",             price: 99,   brand: "Eventide",             category: "Reverb" },
  "crystals":           { name: "Crystals",                price: 99,   brand: "Eventide",             category: "Effect" },
  "mangledverb":        { name: "MangledVerb",             price: 99,   brand: "Eventide",             category: "Reverb" },
  "undulator":          { name: "Undulator",               price: 99,   brand: "Eventide",             category: "Effect" },
  "tricerachorus":      { name: "TriceraChorus",           price: 99,   brand: "Eventide",             category: "Chorus" },

  // ── Softube ───────────────────────────────────────────────────────
  "tsar-1":             { name: "TSAR-1 Reverb",           price: 149,  brand: "Softube",              category: "Reverb" },
  "tsar-1r":            { name: "TSAR-1R Reverb",          price: 99,   brand: "Softube",              category: "Reverb" },
  "british class a":    { name: "British Class A",         price: 299,  brand: "Softube",              category: "Bundle" },
  "british class a compressor": { name: "British Class A Compressor", price: 149, brand: "Softube",   category: "Compressor" },
  "british class a equalizer":  { name: "British Class A EQ",    price: 149,  brand: "Softube",       category: "EQ" },
  "british class a drive":      { name: "British Class A Drive",  price: 99,   brand: "Softube",       category: "Saturation" },
  "american class a":   { name: "American Class A",        price: 99,   brand: "Softube",              category: "Amp Sim" },
  "marshall bluesbreaker": { name: "Marshall Bluesbreaker 1962", price: 99, brand: "Softube",          category: "Amp Sim" },
  "marshall jmp":       { name: "Marshall JMP 2203",       price: 99,   brand: "Softube",              category: "Amp Sim" },
  "marshall plexi":     { name: "Marshall Plexi 1959",     price: 99,   brand: "Softube",              category: "Amp Sim" },
  "marshall silver jubilee": { name: "Marshall Silver Jubilee", price: 99, brand: "Softube",           category: "Amp Sim" },
  "weiss eq":           { name: "Weiss EQ MP",             price: 199,  brand: "Softube",              category: "EQ" },
  "weiss mm":           { name: "Weiss MM-1",              price: 299,  brand: "Softube",              category: "Mastering" },
  "drawmer s73":        { name: "Drawmer S73",             price: 149,  brand: "Softube",              category: "Compressor" },
  "summit audio eqf":   { name: "Summit Audio EQF-100",    price: 149,  brand: "Softube",              category: "EQ" },
  "summit audio grand": { name: "Summit Audio Grand Channel", price: 199, brand: "Softube",            category: "Channel Strip" },
  "summit audio tla":   { name: "Summit Audio TLA-100A",   price: 149,  brand: "Softube",              category: "Compressor" },
  "trident a-range":    { name: "Trident A-Range",         price: 149,  brand: "Softube",              category: "Channel Strip" },
  "saturation knob":    { name: "Saturation Knob",         price: 0,    brand: "Softube",              category: "Saturation" },
  "tube delay":         { name: "Tube Delay",              price: 99,   brand: "Softube",              category: "Delay" },

  // ── SSL Native (via Softube) ──────────────────────────────────────
  "ssl native x-eq":    { name: "SSL Native X-EQ 2",       price: 299,  brand: "SSL",                  category: "EQ" },
  "ssl native x-comp":  { name: "SSL Native X-Comp",       price: 149,  brand: "SSL",                  category: "Compressor" },
  "ssl native channel strip": { name: "SSL Native Channel Strip 2", price: 299, brand: "SSL",           category: "Channel Strip" },
  "ssl native drumstrip":     { name: "SSL Native Drumstrip",  price: 149,  brand: "SSL",              category: "Dynamics" },
  "ssl native vocalstrip":    { name: "SSL Native Vocalstrip", price: 149,  brand: "SSL",              category: "Vocal" },
  "ssl native x-phase":       { name: "SSL Native X-Phase",    price: 99,   brand: "SSL",              category: "Effect" },
  "ssl native x-saturator":   { name: "SSL Native X-Saturator", price: 99,  brand: "SSL",             category: "Saturation" },

  // ── Soundtoys individual ──────────────────────────────────────────
  "fet compressor":     { name: "FET Compressor",           price: 129,  brand: "Soundtoys",           category: "Compressor" },
  "vca compressor":     { name: "VCA Compressor",           price: 129,  brand: "Soundtoys",           category: "Compressor" },
  "opto compressor":    { name: "OPTO Compressor",          price: 129,  brand: "Soundtoys",           category: "Compressor" },
  "i heart ny":         { name: "I Heart NY",               price: 99,   brand: "Soundtoys",           category: "Compressor" },
  "ihny":               { name: "IHNY-2",                   price: 99,   brand: "Soundtoys",           category: "Compressor" },
  "ihny-2":             { name: "IHNY-2",                   price: 99,   brand: "Soundtoys",           category: "Compressor" },
  "comeback kid":       { name: "Comeback Kid",             price: 129,  brand: "Soundtoys",           category: "Delay" },
  "fix flanger":        { name: "Fix Flanger",              price: 99,   brand: "Soundtoys",           category: "Modulation" },
  "fix phaser":         { name: "Fix Phaser",               price: 99,   brand: "Soundtoys",           category: "Modulation" },
  "fix doubler":        { name: "Fix Doubler",              price: 99,   brand: "Soundtoys",           category: "Effect" },
  "parallel aggressor": { name: "Parallel Aggressor",       price: 99,   brand: "Soundtoys",           category: "Compressor" },
  "poltergate":         { name: "Poltergate",               price: 99,   brand: "Soundtoys",           category: "Gate" },

  // ── Native Instruments FX ─────────────────────────────────────────
  "rc 24":              { name: "RC 24",                    price: 79,   brand: "Native Instruments",  category: "Reverb" },
  "rc 48":              { name: "RC 48",                    price: 79,   brand: "Native Instruments",  category: "Reverb" },
  "vc 160":             { name: "VC 160 FX",                price: 99,   brand: "Native Instruments",  category: "Compressor" },
  "vc 2a":              { name: "VC 2A FX",                 price: 99,   brand: "Native Instruments",  category: "Compressor" },
  "vc 76":              { name: "VC 76 FX",                 price: 99,   brand: "Native Instruments",  category: "Compressor" },
  "vari comp":          { name: "Vari Comp",                price: 99,   brand: "Native Instruments",  category: "Compressor" },
  "choral":             { name: "Choral",                   price: 29,   brand: "Native Instruments",  category: "Chorus" },
  "driver":             { name: "Driver",                   price: 29,   brand: "Native Instruments",  category: "Saturation" },
  "dirt":               { name: "Dirt",                     price: 29,   brand: "Native Instruments",  category: "Saturation" },
  "bite":               { name: "Bite",                     price: 29,   brand: "Native Instruments",  category: "Saturation" },
  "freak":              { name: "Freak",                    price: 29,   brand: "Native Instruments",  category: "Effect" },

  // ── Plugin Alliance ───────────────────────────────────────────────
  "shadow hills":       { name: "Shadow Hills Mastering Compressor", price: 149, brand: "Plugin Alliance", category: "Compressor" },
  "bx console ssl":     { name: "bx_console SSL 4000 E",    price: 199,  brand: "Plugin Alliance",     category: "Channel Strip" },
  "bx console focusrite": { name: "bx_console Focusrite SC", price: 199, brand: "Plugin Alliance",     category: "Channel Strip" },
  "bx masterdesk":      { name: "bx_masterdesk",            price: 199,  brand: "Plugin Alliance",     category: "Mastering" },
  "bx opto":            { name: "bx_opto",                  price: 99,   brand: "Plugin Alliance",     category: "Compressor" },
  "bx oberhausen":      { name: "bx_oberhausen",            price: 149,  brand: "Plugin Alliance",     category: "Synth" },
  "lindell 50":         { name: "Lindell 50 Series",        price: 149,  brand: "Plugin Alliance",     category: "Channel Strip" },
  "vertigo vsm":        { name: "Vertigo VSM-3",            price: 149,  brand: "Plugin Alliance",     category: "Saturation" },
  "kirchhoff":          { name: "Kirchhoff-EQ",             price: 149,  brand: "TB Tech",             category: "EQ" },
  "maag eq":            { name: "Maag EQ2",                 price: 99,   brand: "Plugin Alliance",     category: "EQ" },
  "unfiltered audio byome": { name: "BYOME",                price: 149,  brand: "Unfiltered Audio",    category: "Effect" },
  "unfiltered audio lion":  { name: "LION",                 price: 149,  brand: "Unfiltered Audio",    category: "Synth" },
  "unfiltered audio sandman": { name: "Sandman Pro",        price: 99,   brand: "Unfiltered Audio",    category: "Delay" },

  // ── Effects ──────────────────────────────────────────────────────
  "pro-q":              { name: "Pro-Q 3",                 price: 179,  brand: "FabFilter",            category: "EQ" },
  "pro-q 3":            { name: "Pro-Q 3",                 price: 179,  brand: "FabFilter",            category: "EQ" },
  "pro-q3":             { name: "Pro-Q 3",                 price: 179,  brand: "FabFilter",            category: "EQ" },
  "pro-c":              { name: "Pro-C 2",                 price: 179,  brand: "FabFilter",            category: "Compressor" },
  "pro-c 2":            { name: "Pro-C 2",                 price: 179,  brand: "FabFilter",            category: "Compressor" },
  "pro-l":              { name: "Pro-L 2",                 price: 199,  brand: "FabFilter",            category: "Limiter" },
  "pro-l 2":            { name: "Pro-L 2",                 price: 199,  brand: "FabFilter",            category: "Limiter" },
  "pro-mb":             { name: "Pro-MB",                  price: 179,  brand: "FabFilter",            category: "Compressor" },
  "pro-r":              { name: "Pro-R 2",                 price: 199,  brand: "FabFilter",            category: "Reverb" },
  "pro-r 2":            { name: "Pro-R 2",                 price: 199,  brand: "FabFilter",            category: "Reverb" },
  "pro-ds":             { name: "Pro-DS",                  price: 149,  brand: "FabFilter",            category: "De-esser" },
  "pro-g":              { name: "Pro-G",                   price: 99,   brand: "FabFilter",            category: "Gate" },
  "saturn":             { name: "Saturn 2",                price: 199,  brand: "FabFilter",            category: "Saturation" },
  "saturn 2":           { name: "Saturn 2",                price: 199,  brand: "FabFilter",            category: "Saturation" },
  "timeless":           { name: "Timeless 3",              price: 99,   brand: "FabFilter",            category: "Delay" },
  "volcano":            { name: "Volcano 3",               price: 99,   brand: "FabFilter",            category: "Filter" },
  "fabfilter total bundle": { name: "FabFilter Total Bundle", price: 899, brand: "FabFilter",          category: "Bundle" },
  "ozone":              { name: "Ozone 11",                price: 499,  brand: "iZotope",              category: "Mastering" },
  "ozone 11":           { name: "Ozone 11",                price: 499,  brand: "iZotope",              category: "Mastering" },
  "ozone 10":           { name: "Ozone 10",                price: 499,  brand: "iZotope",              category: "Mastering" },
  "neutron":            { name: "Neutron 4",               price: 349,  brand: "iZotope",              category: "Mixing" },
  "neutron 4":          { name: "Neutron 4",               price: 349,  brand: "iZotope",              category: "Mixing" },
  "rx":                 { name: "RX 11",                   price: 399,  brand: "iZotope",              category: "Repair" },
  "rx 11":              { name: "RX 11",                   price: 399,  brand: "iZotope",              category: "Repair" },
  "rx 10":              { name: "RX 10",                   price: 399,  brand: "iZotope",              category: "Repair" },
  "neoverb":            { name: "Neoverb",                 price: 199,  brand: "iZotope",              category: "Reverb" },
  "vocalsynth":         { name: "VocalSynth 2",            price: 199,  brand: "iZotope",              category: "Vocal" },
  "vocalsynth 2":       { name: "VocalSynth 2",            price: 199,  brand: "iZotope",              category: "Vocal" },
  "alloy":              { name: "Alloy 2",                 price: 149,  brand: "iZotope",              category: "Mixing" },
  "h-reverb":           { name: "H-Reverb",                price: 349,  brand: "Waves",                category: "Reverb" },
  "h-delay":            { name: "H-Delay",                 price: 249,  brand: "Waves",                category: "Delay" },
  "ssl":                { name: "SSL 4000",                price: 299,  brand: "Waves",                category: "Channel Strip" },
  "api 2500":           { name: "API 2500",                price: 299,  brand: "Waves",                category: "Compressor" },
  "v-comp":             { name: "V-Comp",                  price: 249,  brand: "Waves",                category: "Compressor" },
  "renaissance maxx":   { name: "Renaissance Maxx",        price: 299,  brand: "Waves",                category: "Bundle" },
  "abbey road":         { name: "Abbey Road Collection",   price: 299,  brand: "Waves",                category: "Bundle" },
  "valhalla reverb":    { name: "Valhalla Reverb",         price: 50,   brand: "ValhallaDSP",          category: "Reverb" },
  "valhalla room":      { name: "ValhallaRoom",            price: 50,   brand: "ValhallaDSP",          category: "Reverb" },
  "valhalla shimmer":   { name: "ValhallaShimmer",         price: 50,   brand: "ValhallaDSP",          category: "Reverb" },
  "valhalla vintage":   { name: "VintageVerb",             price: 50,   brand: "ValhallaDSP",          category: "Reverb" },
  "valhalla delay":     { name: "ValhallaDelay",           price: 50,   brand: "ValhallaDSP",          category: "Delay" },
  "valhalla freq echo": { name: "Freq Echo",               price: 0,    brand: "ValhallaDSP",          category: "Delay" },
  "soundtoys 5":        { name: "SoundToys 5",             price: 499,  brand: "SoundToys",            category: "Bundle" },
  "echoboy":            { name: "EchoBoy",                 price: 199,  brand: "SoundToys",            category: "Delay" },
  "decapitator":        { name: "Decapitator",             price: 149,  brand: "SoundToys",            category: "Saturation" },
  "devil-loc":          { name: "Devil-Loc",               price: 99,   brand: "SoundToys",            category: "Compressor" },
  "crystallizer":       { name: "Crystallizer",            price: 149,  brand: "SoundToys",            category: "Effect" },
  "little alterboy":    { name: "Little AlterBoy",         price: 99,   brand: "SoundToys",            category: "Vocal" },
  "radiator":           { name: "Radiator",                price: 99,   brand: "SoundToys",            category: "Saturation" },
  "filterfreak":        { name: "FilterFreak",             price: 149,  brand: "SoundToys",            category: "Filter" },
  "microshift":         { name: "MicroShift",              price: 99,   brand: "SoundToys",            category: "Effect" },
  "sibilance":          { name: "Sibilance",               price: 99,   brand: "SoundToys",            category: "De-esser" },
  "effectrix":          { name: "Effectrix",               price: 149,  brand: "Sugar Bytes",          category: "Effect" },
  "turnado":            { name: "Turnado",                 price: 99,   brand: "Sugar Bytes",          category: "Effect" },
  "aparillo":           { name: "Aparillo",                price: 99,   brand: "Sugar Bytes",          category: "Synth" },
  "replika":            { name: "Replika XT",              price: 99,   brand: "Native Instruments",   category: "Delay" },
  "raum":               { name: "Raum",                    price: 49,   brand: "Native Instruments",   category: "Reverb" },
  "flair":              { name: "Flair",                   price: 49,   brand: "Native Instruments",   category: "Effect" },
  "phasis":             { name: "Phasis",                  price: 49,   brand: "Native Instruments",   category: "Effect" },
  "klar":               { name: "Klar",                    price: 49,   brand: "Native Instruments",   category: "Reverb" },
  "supercharger":       { name: "Supercharger GT",         price: 49,   brand: "Native Instruments",   category: "Compressor" },
  "transient master":   { name: "Transient Master",        price: 49,   brand: "Native Instruments",   category: "Transient" },
  "limiter no6":        { name: "Limiter No6",             price: 0,    brand: "Tokyo Dawn Records",   category: "Limiter" },
  "nova":               { name: "Nova",                    price: 0,    brand: "Tokyo Dawn Records",   category: "EQ" },
  "kotelnikov":         { name: "Kotelnikov",              price: 0,    brand: "Tokyo Dawn Records",   category: "Compressor" },

  // ── Drums / Beats ────────────────────────────────────────────────
  "addictive drums":    { name: "Addictive Drums 2",       price: 199,  brand: "XLN Audio",            category: "Drums" },
  "addictive drums 2":  { name: "Addictive Drums 2",       price: 199,  brand: "XLN Audio",            category: "Drums" },
  "superior drummer":   { name: "Superior Drummer 3",      price: 399,  brand: "Toontrack",            category: "Drums" },
  "superior drummer 3": { name: "Superior Drummer 3",      price: 399,  brand: "Toontrack",            category: "Drums" },
  "ezdrummer":          { name: "EZdrummer 3",             price: 179,  brand: "Toontrack",            category: "Drums" },
  "ezdrummer 3":        { name: "EZdrummer 3",             price: 179,  brand: "Toontrack",            category: "Drums" },
  "steven slate drums": { name: "Steven Slate Drums 5",    price: 149,  brand: "Steven Slate Audio",   category: "Drums" },
  "slate drums":        { name: "Steven Slate Drums 5",    price: 149,  brand: "Steven Slate Audio",   category: "Drums" },

  // ── DAWs (counted as plugins if folder scanning finds them) ──────
  "ableton live":       { name: "Ableton Live 12 Suite",   price: 749,  brand: "Ableton",              category: "DAW" },
  "fl studio":          { name: "FL Studio All Plugins",   price: 899,  brand: "Image-Line",           category: "DAW" },
  "logic pro":          { name: "Logic Pro",               price: 199,  brand: "Apple",                category: "DAW" },
  "pro tools":          { name: "Pro Tools Studio",        price: 299,  brand: "Avid",                 category: "DAW" },
  "cubase":             { name: "Cubase Pro 13",           price: 579,  brand: "Steinberg",            category: "DAW" },
  "bitwig":             { name: "Bitwig Studio",           price: 399,  brand: "Bitwig",               category: "DAW" },
  "studio one":         { name: "Studio One Pro",          price: 399,  brand: "PreSonus",             category: "DAW" },
  "reason":             { name: "Reason 12",               price: 399,  brand: "Reason Studios",       category: "DAW" },

  // ── DJ Software ──────────────────────────────────────────────────
  "rekordbox":          { name: "Rekordbox DJ",            price: 129,  brand: "Pioneer DJ",           category: "DJ Software" },
  "traktor":            { name: "Traktor Pro 3",           price: 99,   brand: "Native Instruments",   category: "DJ Software" },
  "serato dj":          { name: "Serato DJ Pro",           price: 129,  brand: "Serato",               category: "DJ Software" },
  "virtual dj":         { name: "VirtualDJ",               price: 299,  brand: "Atomix",               category: "DJ Software" },
  "djay pro":           { name: "djay Pro AI",             price: 49,   brand: "algoriddim",           category: "DJ Software" },
};

// Normalize a filename or plugin name for matching
function normalizeName(str) {
  return str
    .toLowerCase()
    .replace(/\.(vst3?|dll|component|aax)$/i, "")
    .replace(/[-_]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

// Look up a plugin filename in the price database
// Returns { name, price, brand, category } or null
function lookupPlugin(filename) {
  const norm = normalizeName(filename);
  // Exact match
  if (PRICES[norm]) return PRICES[norm];
  // Partial match — check if any key is contained in the filename or vice versa
  for (const [key, val] of Object.entries(PRICES)) {
    if (norm.includes(key) || key.includes(norm)) return val;
  }
  return null;
}
